groups:
- name: 主机状态-监控告警
  rules:
  - alert: 主机状态
    expr: up == 0
    for: 15s
    labels:
      status: 非常严重
    annotations:
      summary: "{{$labels.instance}}:服务器宕机"
      description: "{{$labels.instance}}:服务器延时超过5分钟"

  - alert: CPU使用情况
    expr: 100-(avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)* 100) > 70
    for: 15s
    labels:
      status: 一般告警
    annotations:
      summary: "{{$labels.mountpoint}} CPU使用率过高！"
      description: "{{$labels.mountpoint }} CPU使用大于70%(目前使用:{{$value}}%)"

  - alert: 内存使用
    expr: (1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100 > 80
    for: 15s
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} 内存使用率过高！"
      description: "{{$labels.mountpoint }} 内存使用大于80%(已使用:{{$value}}%)"

  - alert: IO性能
    #expr: 100-(avg(irate(node_disk_io_time_seconds_total[1m])) by(instance)* 100) < 60
    expr: (avg(irate(node_disk_io_time_seconds_total[1m])) by(instance) * 100) > 80
    for: 15s
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} 流入磁盘IO使用率过高！"
      description: "{{$labels.mountpoint }} 流入磁盘IO大于80%(目前使用:{{$value}})"

  - alert: 网络
    #expr: ((sum(rate (node_network_receive_bytes_total{device=~"eth0"}[1m]) / 100000) > 300
    expr: sum by (instance) (irate(node_network_receive_bytes_total{device=~"eth0"}[1m]) / 100000) > 200
    for: 1m
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} 流入网络带宽过高！"
      description: "{{$labels.mountpoint }}流入网络带宽持续2分钟高于150M. RX带宽使用率{{$value}}"
 
  - alert: 网络
   # expr: ((sum(rate (node_network_transmit_bytes_total{device=~"eth0"}[1m]) / 100000) > 300
    expr: sum by (instance) (irate(node_network_transmit_bytes_total{device=~"eth0"}[1m]) / 100000) > 200
    for: 1m
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} 流出网络带宽过高！"
      description: "{{$labels.mountpoint }}流出网络带宽持续2分钟高于150M. RX带宽使用率{{$value}}"

  - alert: TCP会话
    expr: node_netstat_Tcp_CurrEstab > 150000
    for: 15s
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} TCP_ESTABLISHED过高！"
      description: "{{$labels.mountpoint }} TCP_ESTABLISHED大于15000%(目前使用:{{$value}}%)"

  - alert: 磁盘容量
    expr: 100-(node_filesystem_free_bytes{fstype=~"ext4|xfs"}/node_filesystem_size_bytes {fstype=~"ext4|xfs"}*100) > 80
    for: 15s
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} 磁盘分区使用率过高！"
      description: "{{$labels.mountpoint }} 磁盘分区使用大于80%(目前使用:{{$value}}%)"

  - alert: ping主机
    expr: probe_success == 0
    for: 15s
    labels:
      status: 严重告警
    annotations:
      summary: "{{$labels.mountpoint}} 主机ping不通了！"
      description: "{{$labels.mountpoint }} 非要逼我报警么{{$value}}%)"

  - alert: NodeProcessBlockedHigh
    expr: node_procs_blocked{job="node"} > 10
    for: 1m
    labels:
      severity: warning
      instance: "{{ $labels.instance }}"
    annotations:
      summary: "instance: {{ $labels.instance }} 当前被阻塞的任务的数量过多"
      description: "Process 当前被阻塞的任务的数量超过 10个"
      value: "{{ $value }}"

  - alert: NodeTimeOffsetHigh
    expr: abs(node_timex_offset_seconds{job="node"}) > 3 * 60
    for: 1m
    labels:
      severity: info
      instance: "{{ $labels.instance }}"
    annotations:
      summary: "instance: {{ $labels.instance }} 时间偏差过大"
      description: "Time 节点的时间偏差超过 3m"
      value: "{{ $value }}"

  - alert: Redis挂了
    expr: redis_up  == 0
    for: 1m
    labels:
      severity: error
    annotations:
      summary: "Redis down (instance {{ $labels.instance }})"
      description: "Redis 挂了啊，mmp\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: OutOfMemory
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Out of memory (instance {{ $labels.instance }})"
      description: "Redis is running out of memory (> 80%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: 复制中断
    expr: delta(redis_connected_slaves[1m]) < 0
    for: 1m
    labels:
      severity: error
    annotations:
      summary: "复制中断 Replication broken (instance {{ $labels.instance }})"
      description: "Redis instance lost a slave\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: TooManyConnections
    expr: redis_connected_clients > 5500
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Too many connections (instance {{ $labels.instance }})"
      description: "Redis instance has too many connections( >5500 )\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: NotEnoughConnections
    expr: redis_connected_clients < 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Not enough connections (instance {{ $labels.instance }})"
      description: "Redis instance should have more connections (> 5)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: 拒绝的连接数
    expr: increase(redis_rejected_connections_total[1m]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Rejected connections (instance {{ $labels.instance }})"
      description: "Some connections to Redis has been rejected\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: redis节点堵塞
    expr: redis_memory_used_bytes < 1024
    for: 3s
    labels:
      severity: error
    annotations:
      summary: "redis 集群节点 (instance {{ $labels.instance }}) 堵塞"
      description: "redis 集群节点内存使用值为\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
